--Q1
SELECT LNAME, FNAME
FROM EMPLOYEE
WHERE (SELECT COUNT (*)
FROM DEPENDENT
WHERE SSN = ESSN) >= 2;
--Q2
SELECT E.FNAME, E.LNAME
FROM EMPLOYEE AS E
WHERE E.SSN IN (SELECT ESSN
FROM DEPENDENT AS D
WHERE E.FNAME = DEPENDENT_NAME AND E.Gender = Gender);
--Q3 NOT SURE
SELECT E.LNAME, E.FNAME
FROM EMPLOYEE AS E
WHERE E.SALARY > ALL(SELECT SALARY
FROM EMPLOYEE
WHERE DNO=5);
--Q4
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE NOT EXISTS (SELECT *
FROM DEPENDENT
WHERE SSN = ESSN);
--Q5
SELECT FNAME, LNAME
FROM EMPLOYEE
WHERE EXISTS (SELECT *
FROM DEPENDENT
WHERE SSN = ESSN)
AND
EXISTS (SELECT *
FROM DEPARTMENT
WHERE SSN = MGR_SSN);