CREATE TABLE Temp_403(Lname VARCHAR(15) NOT NULL, Pname VARCHAR(15) NOT NULL, Hours DECIMAL(3,1) NOT NULL);

INSERT INTO Temp_403
SELECT Lname,Pname, Hours from WORKS_ON AS w, EMPLOYEE as e, PROJECT as p where e.ssn=w.essn and p.pnumber=w.pno;

UPDATE PROJECT SET Plocation='Bellaire', Dnum=5 WHERE PROJECT.Pnumber=10;

UPDATE EMPLOYEE SET Salary=Salary*1.1 FROM DEPARTMENT WHERE DEPARTMENT.Dname='Research' AND EMPLOYEE.Dno=DEPARTMENT.Dnumber;

DELETE FROM EMPLOYEE WHERE EMPLOYEE.Lname='Brown';

ALTER TABLE EMPLOYEE DROP CONSTRAINT employee_super_ssn_fkey;
ALTER TABLE DEPARTMENT DROP CONSTRAINT employee_super_ssn_fkey;
DELETE FROM EMPLOYEE WHERE SSN NOT IN (SELECT ESSN FROM DEPENDENT) ;

BEGIN;
CREATE TABLE A_403(Name VARCHAR(15),id Integer);
INSERT INTO A_403 VALUES('abc',1);
INSERT INTO A_403 VALUES('efg',2);
INSERT INTO A_403 VALUES('xyz',3);
INSERT INTO A_403 VALUES('uvw',4);
INSERT INTO A_403 VALUES('mno',5);
COMMIT;
SELECT * FROM A_403;

BEGIN;
CREATE TABLE B_403(Name VARCHAR(15),id Integer);
INSERT INTO B_403 VALUES('abc',1);
INSERT INTO B_403 VALUES('efg',2);
INSERT INTO B_403 VALUES('xyz',3);
INSERT INTO B_403 VALUES('uvw',4);
INSERT INTO B_403 VALUES('mno',5);
ROLLBACK;
SELECT * FROM B_403;

BEGIN;
CREATE TABLE C_403(Name VARCHAR(15),id Integer);
INSERT INTO C_403 VALUES('abc',1);
INSERT INTO C_403 VALUES('efg',2);
SAVEPOINT S1;
INSERT INTO C_403 VALUES('xyz',3);
INSERT INTO C_403 VALUES('uvw',4);
ROLLBACK TO SAVEPOINT S1;
COMMIT;
SELECT * FROM C_403;