BEGIN;
CREATE TABLE t(Name VARCHAR(15),id Integer);
INSERT INTO t VALUES('abc',1);
INSERT INTO t VALUES('efg',2);
SAVEPOINT S1;
INSERT INTO t VALUES('xyz',3);
INSERT INTO t VALUES('uvw',4);
ROLLBACK TO S1;
SELECT * from t;
END TRANSACTION;

